FROM centos:centos6

RUN yum install -y \
  which \
  createrepo

# Install Amazon CLI
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install awscli

COPY ./publish_rpms.sh /root/publish_rpms.sh
