FROM ruby:2.3

# Install FPM
RUN apt-get update && apt-get install -y \
  ruby-dev \
  make \
  musl-dev \
  libffi-dev \
  tar \
  cpio \
  expect \
  rpm

RUN gem install --no-ri --no-rdoc fpm

# setup gpg keys
COPY .rpmmacros /root/.rpmmacros
COPY rpm-sign.exp /root/rpm-sign.exp
RUN chmod 775 /root/rpm-sign.exp
